version: '3.4'

services:
  auctionservice:
    hostname: auctionservice
    pull_policy: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=auction_postgres;User Id=postgres;Password=postgrespw;Database=auctions
    ports: 
      - 8000:80
  auction_postgres:
    hostname: auction_postgres
    pull_policy: if_not_present
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
     pull_policy: if_not_present
     environment:
       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
       - PGADMIN_DEFAULT_PASSWORD=123456
     ports:
       - 8082:80
     volumes: 
       - pgadmindata:/var/lib/pgadmin
  searchservice:
    hostname: search__service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@search_mongo
      - AuctionServiceUrl=http://auctionservice
    ports: 
      - 8001:80
  search_mongo:
    hostname: search_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27999:27017
    volumes:
      - mongodata:/var/lib/mongodb/data

