version: '3.4'

services:
  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: Backend/AuctionService/Dockerfile
    depends_on: 
      - auction_postgres
      - apprabbitmq
    hostname: auctionservice
    pull_policy: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=auction_postgres;User Id=postgres;Password=postgrespw;Database=auctions
      - Rabbitmq__Host=apprabbitmq
      - Rabbitmq__Port=5672
    ports: 
      - 8000:80
  searchservice:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: Backend/SearchService/Dockerfile
    depends_on: 
      - search_mongo
      - apprabbitmq
    hostname: search__service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@search_mongo
      - AuctionServiceUrl=http://auctionservice
      - Rabbitmq__Host=apprabbitmq
      - Rabbitmq__Port=5672
    ports: 
      - 8001:80
  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: Backend/IdentityService/Dockerfile
    depends_on: 
      - auction_postgres
    hostname: identityservice
    pull_policy: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=auction_postgres;User Id=postgres;Password=postgrespw;Database=auctions
    ports: 
      - 8002:80
  auction_postgres:
    image: postgres
    hostname: auction_postgres
    pull_policy: if_not_present
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
     image: dpage/pgadmin4
     pull_policy: if_not_present
     environment:
       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
       - PGADMIN_DEFAULT_PASSWORD=123456
     ports:
       - 8082:80
     volumes: 
       - pgadmindata:/var/lib/pgadmin
  search_mongo:
    image: mongo
    hostname: search_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27999:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  apprabbitmq:
    hostname: apprabbitmq
    image: rabbitmq:3-management-alpine
    ports: 
      - 56720:5672
      - 58000:15672 

