version: '3.4'

services:
  gateway:
    container_name: gateway
  auctionservice:
    container_name: auctionservice
  searchservice:
    container_name: searchservice
  identityservice:
    container_name: identityservice
  auction_postgres:
    container_name: auction_postgres
  pgadmin:
    container_name: pgadmin
  search_mongo:
    container_name: search_mongo
  apprabbitmq:
    container_name: apprabbitmq
volumes:
  pgdata:
  pgadmindata:
  mongodata: